services:
  - type: web
    name: virtual-cosmos-server
    runtime: node
    rootDir: server
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: PORT
        value: 3001
      - key: CLIENT_URL
        sync: false
